AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api-services

  Sample SAM Template for api-services

# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

Resources:
  ApiServices:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
