Mappings:
  ECRDLTImage: 
    ImageURI: 
      Value: public.ecr.aws/x2t0y6c0/aws-dlt/taurus-tester

Resources:
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: 
        Fn::Sub: "${AWS::StackName}-load-tester-logs"
      RetentionInDays: 5
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  ECSClusterDLT:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: DLT-ECS-Cluster
  
  ECSDLTBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: "${AWS::StackName}dltbucket"

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:*"
                Resource: 
                - !GetAtt ECSDLTBucket.Arn
                - !Sub "${ECSDLTBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - "logs:*"
                Resource: 
                  - !GetAtt ECSLogGroup.Arn
                  - !Sub "${ECSLogGroup.Arn}:log-stream:*"

  ECSClusterTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Image: !FindInMap [ ECRDLTImage, ImageURI, Value ]
          Name:
            Fn::Sub: "${AWS::StackName}-load-tester"
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
      Cpu: '2048'
      Memory: '4096'
      Family: !Join
        - ''
        - - !Ref AWS::StackName
          - '-task-family'
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ECSTaskRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
    DependsOn: ECSClusterDLT
