AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'task-runner

  Sample SAM Template for task-runner

  '
Resources:
  TaskRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://dlt-codes-akash/aws-dlt/1.0.0/8d25d6e6dd5b84d15d530819caa4a32a
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Timeout: 180
    Metadata:
      SamResourceId: TaskRunnerFunction
